version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}
    container_name: blog_app_db
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      blog_network:
        ipv4_address: 173.18.1.10

networks:
  blog_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.18.1.0/16
